on:
  push:
      branches: [ main ]
  workflow_dispatch:
jobs:
 build:
  run-on:ubuntu-latest
  steps:
   -name:checkout code
    uses:actions/checkout@v4
  -name:set up Node.js
   with
    node-version:'18'
   uses:actions/setup-node@v4
  -name:build dependencies
   run:npm install
  -name:build application
   run:echo"build application..."
 test:
  run-on:ubuntu-latest
  need:build
  steps:
   -name:checkout code
    use:actions/checkout@v4
  -name:install dependencies
   run:npm install
  -name:run test
   run:npm test
deploy:
 run-on:ubuntu-latest
 need:test
 steps:
  -name:checkout code
   uses:action/checkout@v4
  -name:deploy the application
   run:echo"deploy the application..."
  
    
   
